#!/bin/bash
cat \
src/NyAs3Utils.js \
src/FLARArrayUtil.js \
src/FLARException.js \
src/FLARMat.js \
src/FLARRgbPixelReader.js \
src/NyARHistogramAnalyzer.js \
src/NyARPca2d.js \
src/NyARRasterReader.js \
src/NyARTypes.js \
src/FLARRasterFilter.js \
src/FLARTypes.js \
src/NyARLabel.js \
src/FLARLabeling.js \
src/NyARParam.js \
src/FLARParam.js \
src/NyARRaster.js \
src/FLARRaster.js \
src/NyARCode.js \
src/FLARCode.js \
src/NyARMatch.js \
src/NyARRasterAnalyzer.js \
src/FLARRasterAnalyzer.js \
src/NyARRasterFilter.js \
src/NyARSquareDetect.js \
src/FLARSquareDetect.js \
src/NyARTransMat.js \
src/FLARTransMat.js \
src/NyARUtils.js \
src/NyARIdMarker.js \
src/NyARPickup.js \
src/FLARProcessor.js \
src/NyARDetector.js \
src/FLARDetector.js \
src/FLARIdMarkerDetector.js \
src/NyARSingleMarkerProcesser.js \
src/NyUtils.js \
> JSARToolKit.js
